<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-0356DV5C" ignored="0" name="t2" tests="4" failures="2" timestamp="2020-11-15T09:18:41 CST" time="14.465" errors="0">
  <testcase name="test1" time="0.004" classname="com.webtest.testCases.LoginTest"/>
  <testcase name="test2" time="0.001" classname="com.webtest.testCases.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at com.webtest.testCases.LoginTest.test2(LoginTest.java:30)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.0" classname="com.webtest.testCases.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [3] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [1]
at com.webtest.testCases.LoginTest.test3(LoginTest.java:34)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test4" time="0.0" classname="com.webtest.testCases.LoginTest"/>
</testsuite> <!-- t2 -->
